# Generated by Django 5.0.1 on 2026-01-22 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_ticket_type_is_acti_a1b2c3_idx_ticket_type_is_acti_ba16c9_idx_and_more'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='area',
            field=models.CharField(help_text='e.g., Food Court, Main Hall', max_length=100),
        ),
        migrations.AlterField(
            model_name='booth',
            name='zone',
            field=models.CharField(blank=True, help_text='e.g., A, B, C', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Show on public vendors page'),
        ),
        # Skip indexes - they're already defined in model Meta
    ]
