# Generated by Django 5.0.1 on 2026-01-22 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_ticket_type_is_acti_a1b2c3_idx_ticket_type_is_acti_ba16c9_idx_and_more'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='area',
            field=models.CharField(help_text='e.g., Food Court, Main Hall', max_length=100),
        ),
        migrations.AlterField(
            model_name='booth',
            name='zone',
            field=models.CharField(blank=True, help_text='e.g., A, B, C', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Show on public vendors page'),
        ),
        migrations.AddIndex(
            model_name='booth',
            index=models.Index(fields=['booth_code'], name='booths_booth_c_6815e7_idx'),
        ),
        migrations.AddIndex(
            model_name='booth',
            index=models.Index(fields=['area', 'zone'], name='booths_area_0583ba_idx'),
        ),
        migrations.AddIndex(
            model_name='boothassignment',
            index=models.Index(fields=['vendor'], name='booth_assig_vendor__2076c7_idx'),
        ),
        migrations.AddIndex(
            model_name='boothassignment',
            index=models.Index(fields=['assigned_at'], name='booth_assig_assigne_ffe42e_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorprofile',
            index=models.Index(fields=['booth_status', 'is_active'], name='vendor_prof_booth_s_54c751_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorprofile',
            index=models.Index(fields=['category', 'is_public'], name='vendor_prof_categor_b703e9_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorsetuplog',
            index=models.Index(fields=['vendor', 'scanned_at'], name='vendor_setu_vendor__8cef63_idx'),
        ),
    ]
