# Generated by Django 5.0.1 on 2026-01-22 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_ticket_type_is_acti_a1b2c3_idx_ticket_type_is_acti_ba16c9_idx_and_more'),
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='passrecord',
            index=models.Index(fields=['user', 'pass_type'], name='pass_record_user_id_53eee2_idx'),
        ),
        migrations.AddIndex(
            model_name='passrecord',
            index=models.Index(fields=['ticket', 'pass_type'], name='pass_record_ticket__38c92b_idx'),
        ),
        migrations.AddIndex(
            model_name='passrecord',
            index=models.Index(fields=['status'], name='pass_record_status_7fd672_idx'),
        ),
    ]
