# Generated by Django 5.0.1 on 2026-01-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventconfig',
            options={'verbose_name': 'Event Configuration', 'verbose_name_plural': 'Event Configurations'},
        ),
        # Only add indexes that don't rely on missing columns
        migrations.AddIndex(
            model_name='contactsubmission',
            index=models.Index(fields=['subject', 'is_read'], name='contact_sub_subject_f1e020_idx'),
        ),
        migrations.AddIndex(
            model_name='contactsubmission',
            index=models.Index(fields=['created_at'], name='contact_sub_created_54b02f_idx'),
        ),
        migrations.AddIndex(
            model_name='sponsor',
            index=models.Index(fields=['tier', 'is_active'], name='sponsors_tier_96271e_idx'),
        ),
    ]
