# Generated by Django 5.0.1 on 2026-01-22 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0001_initial'),
        ('tickets', '0002_rename_ticket_type_is_acti_a1b2c3_idx_ticket_type_is_acti_ba16c9_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='scansession',
            index=models.Index(fields=['scanner', 'is_active'], name='scan_sessio_scanner_2c4962_idx'),
        ),
        migrations.AddIndex(
            model_name='scansession',
            index=models.Index(fields=['started_at'], name='scan_sessio_started_bcc678_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketscanlog',
            index=models.Index(fields=['ticket', 'scanned_at'], name='ticket_scan_ticket__cc31b6_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketscanlog',
            index=models.Index(fields=['result', 'scanned_at'], name='ticket_scan_result_bcc008_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketscanlog',
            index=models.Index(fields=['scanner', 'scanned_at'], name='ticket_scan_scanner_5f8371_idx'),
        ),
    ]
