# Generated by Django 5.0.1 on 2026-01-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('tickets', '0002_rename_ticket_type_is_acti_a1b2c3_idx_ticket_type_is_acti_ba16c9_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['order', 'status'], name='payment_att_order_i_dd2ec6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['stripe_payment_intent_id'], name='payment_att_stripe__eec25c_idx'),
        ),
        migrations.AddIndex(
            model_name='stripeevent',
            index=models.Index(fields=['stripe_event_id'], name='stripe_even_stripe__92510f_idx'),
        ),
        migrations.AddIndex(
            model_name='stripeevent',
            index=models.Index(fields=['event_type', 'processed'], name='stripe_even_event_t_7192d5_idx'),
        ),
        migrations.AddIndex(
            model_name='stripeevent',
            index=models.Index(fields=['received_at'], name='stripe_even_receive_925e39_idx'),
        ),
    ]
