# Generated by Django 5.0.1 on 2026-01-22 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tickettype',
            new_name='ticket_type_is_acti_ba16c9_idx',
            old_name='ticket_type_is_acti_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='tickettype',
            new_name='ticket_type_slug_d24891_idx',
            old_name='ticket_type_slug_d4e5f6_idx',
        ),
    ]
